### ISSUE TITLE
Is it still up to date?

### ISSUE THREAD

**Issue by mohammedzamakhan** [benbraou/is-angular-ivy-ready#11]

**Comment by benbraou** [comment]
Hello @mohammedzamakhan . Sorry, I had limited access to my laptop in the last days.
Yes, the site is always up to date. It uses an [API](https://github.com/benbraou/ivy-status-api) that periodically parses [STATUS.md](https://github.com/angular/angular/blob/master/packages/core/src/render3/STATUS.md) . The angular team update that file when relevant
