### ISSUE TITLE
Filter pending features

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [benbraou/is-angular-ivy-ready#12]
Now that we're getting close to completion, it would be nice to filter the list on pending features. The existing pending text could be turned into an interactive control or a new control could be added. Only feature groups with pending features should be shown, and visible feature groups should only show the pending features.

**Comment by benbraou** [comment]
Thanks @tobi-or-not-tobi. Sorry for the delay, I was away from Github for a while
`ivy` is used by default since version 9. I ll update the app to show that.
