### ISSUE TITLE
xlink:href attribute

### ISSUE THREAD

**Issue by TheLexI** [benbraou/is-angular-ivy-ready#15]
write in teplate 
`<svg class="xicon"><use xlink:href="/assets/symbols/symbols.svg#menu"></use></svg>`

and get on page 
`<svg class="xicon"><use :xlink:href="/assets/symbols/symbols.svg#menu"></use></svg>`

ivy works very strange

**Comment by benbraou** [comment]
ivy is used by default since version 9. I ll update the app to show that. Sorry for the delay, I was away from Github for a while
