### ISSUE TITLE
Enable server side rendering

### ISSUE THREAD

**Issue by benbraou** [benbraou/is-angular-ivy-ready#6]

**Comment by pankajparkar** [comment]
What exactly you meant to say here? You want to enable SSR for this project?

**Comment by benbraou** [comment]
Indeed, it was about server side rendering which is already implemented now 😄.
Closing the issue as it is outdated. Sorry about that

**Comment by pankajparkar** [comment]
Latest version isn't deployed or what? because I expected to see `html` when I did `View Source`

**Comment by benbraou** [comment]
@pankajparkar you are right. Great catch! 
The latest version is indeed deployed so there is definitely something wrong here
I will gladly accept PR for this :)
