### ISSUE TITLE
Enhance UX with current SSR

### ISSUE THREAD

**Issue by benbraou** [benbraou/is-angular-ivy-ready#9]
Thanks to #6, SSR is now enabled for this project (not yet deployed).

The steps to test this locally is:
```
yarn build
yarn start-ssr
```
However, the call to the Ivy Status API is still performed on client side even if the initial static page was rendered on the server.

![current](https://user-images.githubusercontent.com/14368835/39541553-627aa55e-4e46-11e8-9a26-4138ec4dbdfd.gif)

Currently, I have identified the following enhancements :
- [x] Use the `TransferState` API to transfer Ivy status data from the server to the client (fixed with 9379b2304e921c51bf59e92bf5d36067ec2f20d0)
- [x] Make `SpinnerCaptionDirective` work on server side (otherwise the logic of adding the percentage inside the SVG circle of `mat-progress-spinner` will only occur on client side and causes an annoying 'refresh') ('fixed' with 9379b2304e921c51bf59e92bf5d36067ec2f20d0)
- [x] Investigate (+fix) why we have the following bug:
       - We have the initial page rendered correctly in the browser
      - we force a refresh (F5) and keep the url `http://localhost:4000/#/status`
      - We see that for a while we have incorrect styles displayed(seems that the tablet styles are being applied instead of the desktop style. By the way, all styles are handled with angular FlexLayout)

![bug](https://user-images.githubusercontent.com/14368835/39542589-405c3fc0-4e49-11e8-92e2-0edad9e04204.gif)

- [ ]  Display of feature-group overview is broken. In the picture attached below, the text `0 features completed` wraps, but it should not have. This is because in `app-feature-group-overview.component.html`, we are using `<span fxHide.lt-md>features </span>`. On desktop view, this span is visible and @angular/flex-layout applies to it `display:bock`. This is breaking the display

- [ ]  Expansion panel is expanded + styles are broken. It should be collapsed by default
![screen shot 2018-05-09 at 19 19 17](https://user-images.githubusercontent.com/14368835/39829204-f1f545dc-53bd-11e8-8c8a-367e6bb33e8c.png)

**Comment by nartc** [comment]
I'll take a look when I have some spare time. That's annoying lol xD

Enjoy your vacation!

**Comment by pankajparkar** [comment]
I spent hour on it, found that it could be related to performance related issue. `fxLayout` doesn't work that well for 100+ rows here is an [example](https://stackblitz.com/edit/angular-flex-layout-seed-jmob2p?file=app%2Ftest.component.ts). This seems to be an [related issue](https://github.com/angular/flex-layout/issues/233) 

Here is the [performance optimization tips](https://github.com/angular/flex-layout/wiki/Performance-Considerations) on Angular FlexLayout

**Comment by benbraou** [comment]
Thanks @pankajparkar for your time.
I checked what is happening in the server side rendered html and I see the problem.
Generally, `@angular/flex-layout` injects the inline style based on the media query activation.
However, for server-side rendering, the server -for now- has no information about the viewport size. `@angular/flex-layout` handles this limitation  by generating css classes and media queries.
The problem was with the order of the css media queries generated. 
`@media (min-width: 600px)  => cards width is 100%` was applied after `@media (min-width: 960px)  => cards width is 40%`
In case of rules collision, the browser choses the last media query applied. Therefore, in the desktop, we were having the tablet mode...
I was trying to use a mobile first approach. I switched to desktop first, and it fixes the issue.
<img width="435" alt="screen shot 2018-05-09 at 19 12 54" src="https://user-images.githubusercontent.com/14368835/39828918-0b921a34-53bd-11e8-94fe-96b7b2a25421.png">

**Comment by benbraou** [comment]
I have added two new issues in  https://github.com/benbraou/is-angular-ivy-ready/issues/9#issue-319669410
Feel free to help. I am not planning to work no them in the immediate future.

**Comment by pankajparkar** [comment]
I can't see new issues, am I missing something? ;)

**Comment by benbraou** [comment]
I will work on this tomorrow if no PR is provided before. Hopefully, SSR will be deployed by the end of this weekend
